version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sistema
      POSTGRES_PASSWORD: 2045
      POSTGRES_DB: pesquisa_livros
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://sistema:2045@db:5432/pesquisa_livros
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  pgdata:
